dist: xenial
sudo: required

language: go
go_import_path: github.com/opensds/multi-cloud
go:
  - 1.13
  - tip

services:
  - docker

env:
  matrix:
    - TARGET=amd64
      GO111MODULE=on

before_install:
  - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.31.0
  - wget -qO - https://packages.confluent.io/deb/5.3/archive.key | sudo apt-key add -
  - wget -q -O- "https://download.ceph.com/keys/release.asc" | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://packages.confluent.io/deb/5.3 stable main"
  - sudo apt-add-repository "deb https://download.ceph.com/debian-luminous/ xenial main"
  - sudo apt-get update && sudo apt-get install -y libradosstriper-dev librados-dev librdkafka-dev

matrix:
  fast_finish: true
  allow_failures:
    - go: tip

install:
  # Build SODA multi-cloud container images
  - make docker
  - docker-compose up -d

script:
  - golangci-lint run
  - ./install/CI/coverage
  - ./install/CI/test

after_success:
  # Clean SODA multi-cloud built data
  - bash <(curl -s https://codecov.io/bash)
  - make clean
