apiVersion: v1
kind: Service
metadata:
  labels:
    io.soda.service: api
  name: api
spec:
  type: NodePort      
  ports:
    - name: "8089"
      nodePort: 30099
      port: 8089
      targetPort: 8089
  selector:
    io.soda.service: api
status:
  loadBalancer: {}

