apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: api
    spec:
      containers:
        - env:
#            - name: MICRO_REGISTRY
#              value: mdns
#            - name: MICRO_SERVER_ADDRESS
#              value: :8089
            - name:  MICRO_REGISTRY
              value:  kubernetes
            - name: MICRO_SERVER_ADDRESS           
              value: 0.0.0.0:8089
            - name: MICRO_BROKER_ADDRESS
              value: 0.0.0.0:9091               
            - name: OS_AUTH_AUTHSTRATEGY
              value: keystone
            - name: OS_AUTH_URL
              value: http://192.168.20.108/identity
            - name: OS_PASSWORD
              value: opensds@123
            - name: OS_PROJECT_NAME
              value: service
            - name: OS_USERNAME
              value: opensds
            - name: OS_USER_DOMIN_ID
              value: Default
            - name: SVC_FLAG
              value: ctrl
            - name: TRANSFER_SPEED_MIN
              value: "10"
          image: sodafoundation/multi-cloud-api:v9
          name: api
          ports:
            - containerPort: 8089
          resources: {}
          volumeMounts:
            - mountPath: /etc/ssl/certs
              name: api-hostpath0
            - mountPath: /etc/localtime
              name: api-hostpath1
            - mountPath: /var/log/multi-cloud
              name: api-hostpath2
            - mountPath: /etc/multi-cloud
              name: config-volume
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /etc/ssl/certs
          name: api-hostpath0
        - hostPath:
            path: /etc/localtime
          name: api-hostpath1
        - hostPath:
            path: /var/log/multi-cloud
          name: api-hostpath2
        - name: config-volume
          configMap:
            name: multicloud-config
status: {}

