apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: datastore:27017
#            - name: MICRO_REGISTRY
#              value: mdns
#            - name: MICRO_SERVER_ADDRESS
#              value: :8091
            - name:  MICRO_REGISTRY
              value:  kubernetes
            - name: MICRO_SERVER_ADDRESS
              value: 0.0.0.0:9090
            - name: MICRO_BROKER_ADDRESS
              value: 0.0.0.0:9091
  
          image: sodafoundation/multi-cloud-backend:v9
          name: backend
          ports:
            - containerPort: 8091
          resources: {}
          volumeMounts:
            - mountPath: /etc/localtime
              name: backend-hostpath0
            - mountPath: /var/log/multi-cloud
              name: backend-hostpath1
            - mountPath: /etc/multi-cloud
              name: config-volume
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /etc/localtime
          name: backend-hostpath0
        - hostPath:
            path: /var/log/multi-cloud
          name: backend-hostpath1
        - name: config-volume
          configMap:
            name: multicloud-config
status: {}
