apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: block
  name: block
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: block
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: block
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: datastore:27017
#            - name: MICRO_REGISTRY
#              value: mdns
#            - name: MICRO_SERVER_ADDRESS
#              value: :8092
            - name:  MICRO_REGISTRY
              value:  kubernetes
            - name: MICRO_SERVER_ADDRESS
              value: 0.0.0.0:9090
            - name: MICRO_BROKER_ADDRESS
              value: 0.0.0.0:9091 
          image: sodafoundation/multi-cloud-block:v9
          name: block
          resources: {}
          volumeMounts:
            - mountPath: /etc/localtime
              name: block-hostpath0
            - mountPath: /var/log/multi-cloud
              name: block-hostpath1
            - mountPath: /etc/config
              name: config-volume
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /etc/localtime
          name: block-hostpath0
        - hostPath:
            path: /var/log/multi-cloud
          name: block-hostpath1
        - name: config-volume
          configMap: 
            name: multicloud-config
status: {}

