apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.soda.service: block
    app: soda-backend
  name: block
spec:
  replicas: 2
  selector:
    matchLabels:
      io.soda.service: block
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.soda.service: block
        app: soda-backend
    spec:
      affinity:
         podAntiAffinity:
           requiredDuringSchedulingIgnoredDuringExecution:
           - labelSelector:
               matchExpressions:
               - key: "app"
                 operator: In
                 values:
                 - soda-block
             topologyKey: "kubernetes.io/hostname"
      containers:
        - env:
            - name: DB_HOST
              value: mongodb-0-service,mongodb-1-service,mongodb-2-service/?replicaSet=rs0
            - name:  MICRO_REGISTRY
              value:  kubernetes
            - name: MICRO_SERVER_ADDRESS
              value: 0.0.0.0:9090
            - name: MICRO_BROKER_ADDRESS
              value: 0.0.0.0:9091 
          image: sodafoundation/multi-cloud-block:v9
          name: block
          resources: {}
          volumeMounts:
            - mountPath: /etc/localtime
              name: block-localtime
            - mountPath: /var/log/multi-cloud
              name: block-logs
            - mountPath: /etc/config
              name: config-volume
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /etc/localtime
          name: block-localtime
        - hostPath:
            path: /var/log/multi-cloud
          name: block-logs
        - name: config-volume
          configMap: 
            name: multicloud-config

