apiVersion: v1
kind: Service
metadata:
  labels:
    io.soda.service: dataflow
  name: dataflow
spec:
  ports:
    - name: "8094"
      port: 8094
      targetPort: 8094
  selector:
    io.soda.service: dataflow
status:
  loadBalancer: {}
