apiVersion: v1
kind: Service
metadata:
  labels:
    io.soda.service: file
  name: file
spec:
  ports:
    - name: "8092"
      port: 8092
      targetPort: 8092
  selector:
    io.soda.service: file
status:
  loadBalancer: {}
