apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: kafka-svc
  name: kafka-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka-svc
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: kafka-svc
    spec:
      containers:
        - env:
            - name: KAFKA_PORT
              value: "9092"    
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka-svc:9092
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper:2181
          image: wurstmeister/kafka:2.11-2.0.1
          name: kafka-svc
          ports:
            - containerPort: 9092
          resources: {}
      restartPolicy: Always
status: {}
