apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: datastore
  name: datastore
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: datastore
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: datastore
    spec:
      containers:
        - image: mongo
          name: datastore
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /tmp/mongodb/
              name: mongo-data
          resources: {}
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /root/multi-cloud/mongo-data
            type: DirectoryOrCreate      
          name: mongo-data
status: {}
