apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.soda.service: zookeeper
  name: zookeeper
spec:
  ports:
    - name: "2181"
      port: 2181
      targetPort: 2181
  selector:
    io.soda.service: zookeeper
status:
  loadBalancer: {}
