version: '2'

services:

  api:
    image: opensdsio/multi-cloud-api-debug
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/localtime:/etc/localtime
      - .:/opt/go/src/github.com/opensds/multi-cloud
    ports:
      - "8089:8089"
      - "2345:2345"
    environment:
      - MICRO_SERVER_ADDRESS=:8089
      - MICRO_REGISTRY=mdns
      - OS_AUTH_AUTHSTRATEGY=keystone
      - OS_AUTH_URL=http://192.168.2.24/identity
      - OS_USER_DOMIN_ID=Default
      - OS_USERNAME=multicloud
      - OS_PASSWORD=opensds@123
      - OS_PROJECT_NAME=service
    #build: .
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    entrypoint: dlv --listen=:2345 --headless=true --api-version=2 exec /api-debug
    expose:
      - "8089"
      - "2345"